//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopApi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    [Authorize(Roles = "Administrator")]
    public partial class Groups
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Groups()
        {
            this.Products = new HashSet<Products>();
        }
        [HiddenInput(DisplayValue = false)]
        public int Id { get; set; }
        [Required]
        [DisplayName("Имя")]
        [RegularExpression(@"[A-Za-z]{2,40}", ErrorMessage = "Некорректное имя")]
        public string Name { get; set; }
        [Required]
        [DisplayName("Путь к картинке")]
        [RegularExpression(@"[A-za-z-_0-9]{1,30}[.img|.jpg|.png]", ErrorMessage = "Некорректный путь")]
        public string ImgSrc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Products> Products { get; set; }
    }
}
